# Generated by Django 4.1.1 on 2022-10-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0002_fiche'),
    ]

    operations = [
        migrations.AddField(
            model_name='liste',
            name='fiche',
            field=models.ManyToManyField(to='cours.fiche'),
        ),
    ]
