# Generated by Django 4.1.1 on 2022-10-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='parametreGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backgroud_color', models.CharField(max_length=7)),
                ('fonction_color', models.CharField(max_length=7)),
                ('grid', models.BooleanField()),
                ('name_xaxis', models.CharField(max_length=50)),
            ],
        ),
    ]
